# --- Configuration for the Forecasting Pipeline ---

# Processing Controls
max_skus_to_process: null # Set to a number (e.g., 10) for testing, or null to run all
max_workers: 4 # Number of parallel processes. Start with os.cpu_count() or lower.

# Data Thresholds
min_data_points_prophet: 30
min_data_points_lstm: 60
test_days: 30
sporadic_threshold: 0.60

# Model Parameters
sma_window: 28
holiday_types:
  - "National holiday"
  - "Optional holiday"

lstm:
  n_steps: 30
  epochs: 50
  batch_size: 32

QUANTILES: [0.1, 0.5, 0.9]
MC_DROPOUT_SAMPLES: 50

# Inventory Management Parameters
inventory:
  avg_lead_time_days: 21
  moq: 20
  service_level: 0.95
  holding_cost_percentage: 0.10
  ordering_cost_percentage: 0.30

# Prophet Tuning: Optuna will handle the parameter ranges
prophet_tuning_timeout: 120 # Timeout in seconds for Prophet tuning per SKU

# File paths for input and output data
file_paths:
  sales: "./home/jupyter/sales_data_complete___daily_drill_down_2025-05-29T12_37_43.113222731+05_30.csv"
  inventory: "./home/jupyter/query_result_2025-05-28T18_02_43.550629445+05_30.csv"
  holidays: "./home/jupyter/indian_holidays.csv"
  output: "./home/jupyter/multi_sku_forecasting_final.csv"
  daily_forecast: "./home/jupyter/daily_forecasts_final.csv"
